@startuml
'https://plantuml.com/class-diagram

skinparam class {
  ' задаем светлозеленый цвет для фона классов по умолчанию
  BackgroundColor LightGreen
  ' задаем синий цвет для связей классов по умолчанию
  ArrowColor      Green
  ' задаем красный цвет для контуров классов по умолчанию
  BorderColor     Green
}

package "controller" {
    +abstract class Controller{
             #view:View
             #typeAction:Actions
             +Actions:enum
             +setTypeAction(act:Actions):void
             +process(tasks:AbstractTaskList):int
             +getTypeAction():Actions
             +getIntAction():int
             +isThatAction(e:Actions):boolean
    }
    enum Actions {
        MENU
        ADD_NEW_TASK
        EDIT_TASK
        DELETE_TASK
        SHOW_ALL_TASK
        SHOW_ALL_CALENDAR
        SHOW_CALENDAR
        SAVE
        LOAD
        END_ACT
        +abstract getInt():int
    }

    +class MenuController extends Controller {
          -tasks:AbstractTaskList
          -controllers:List<Controller>
          +getTaskList():AbstractTaskList

          +isThatAction(e:Actions):boolean
          +getTypeAction():Actions
          +process(tasks:AbstractTaskList):int
    }
    MenuController "0..1" o--[#red]- "0..*" Controller #text:red
    Controller *-[#blue]- Actions
    together {
        class MenuController
        class Controller
    }


    +class AddTaskController extends Controller {
          +isThatAction(e:Actions):boolean
          +process(tasks:AbstractTaskList):int
    }
    skinparam groupInheritance 3


    +class AllCalendarController extends Controller{
           +isThatAction(e:Actions):boolean
           +process(tasks:AbstractTaskList):int
    }

    +class CalendarController extends Controller {
           +process(tasks:AbstractTaskList):int
    }

    +class DeleteTaskController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class EditTaskController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class ExitController extends SaveController {
          +process(tasks:AbstractTaskList):int
    }

    +class LoadController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class SaveController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class ShowAllTaskController extends Controller {
          +process(tasks:AbstractTaskList):int
    }
}

@enduml