@startuml
'https://plantuml.com/class-diagram

skinparam class {
  ' задаем светлозеленый цвет для фона классов по умолчанию
  BackgroundColor LightGreen
  ' задаем синий цвет для связей классов по умолчанию
  ArrowColor      Green
  ' задаем красный цвет для контуров классов по умолчанию
  BorderColor     Green
}

package "view" {
    +interface View {
        +abstract printInfo(list:AbstractTaskList):int
    }

    +class AddTaskView implements View {
          +printInfo(list:AbstractTaskList):int
          +getTaskFromConsole():Task
    }

    +class AllCalendarView extends CalendarView {
          +printInfo(list:AbstractTaskList):int
    }

    +class CalendarView implements View {
          +printInfo(list:AbstractTaskList):int
          +printCalendar(list:AbstractTaskList, start:LocalDateTime, end:LocalDateTime):void
    }

    +class DeleteTaskView extends ShowAllTaskView {
          +printInfo(list:AbstractTaskList):int
    }

    +class EditTaskView extends ShowAllTaskView {
          +printInfo(list:AbstractTaskList):int
          +printEditAction(editTask:Task):void
          +printEditingTask(editTask:Task, continued:boolean):boolean
    }

    +class LoadViw implements View {
          -static logger:Logger
          +printInfo(list:AbstractTaskList):int
    }

    +class MenuView implements View {
          -actionMenu:String[]
          -notAvailAbleActions:HashSet<Integer>
          +printInfo(list:AbstractTaskList):int
    }

    +class SaveView implements View {
          -static logger:Logger
          +printInfo(list:AbstractTaskList):int
    }

    +class ShowAllTaskView implements View {
          +printInfo(list:AbstractTaskList):int
    }

    +class Inputer {
              -static reader:BufferedReader
              +DateFormat:enum
              +static readInt():int
              +static readLine():String
              +static readBool():boolean
              +static readBoolFromLine():boolean
              +static readDateFromString(date:String):LocalDateTime
              +static readDateFromLine():LocalDateTime
        }
        enum DateFormat {
             DEF
             DEF_POINTS
             +abstract getFormat():DateTimeFormatter
        }
        Inputer *-- DateFormat
        AddTaskView ..> Inputer
        CalendarView ..> Inputer
        DeleteTaskView ..> Inputer
        EditTaskView ..> Inputer
        MenuView ..> Inputer
        SaveView ..> Inputer
}

@enduml