@startuml
'https://plantuml.com/class-diagram

package "controller" {
    +abstract class Controller{
             #view:View
             #typeAction:Actions
             +Actions:enum
             +setTypeAction(act:Actions):void
             +process(tasks:AbstractTaskList):int
             +getTypeAction():Actions
             +getIntAction():int
             +isThatAction(e:Actions):boolean
    }
    enum Actions {
        MENU
        ADD_NEW_TASK
        EDIT_TASK
        DELETE_TASK
        SHOW_ALL_TASK
        SHOW_ALL_CALENDAR
        SHOW_CALENDAR
        SAVE
        LOAD
        END_ACT
        +abstract getInt():int
    }

    +class Inputer {
          -static reader:BufferedReader
          +DateFormat:enum
          +static readInt():int
          +static readLine():String
          +static readBool():boolean
          +static readBoolFromLine():boolean
          +static readDateFromString(date:String):LocalDateTime
          +static readDateFromLine():LocalDateTime
    }
    enum DateFormat {
         DEF
         DEF_POINTS
         +abstract getFormat():DateTimeFormatter
    }

    +class MenuController extends Controller {
          -tasks:AbstractTaskList
          -controllers:List<Controller>
          +getTaskList():AbstractTaskList

          +isThatAction(e:Actions):boolean
          +getTypeAction():Actions
          +process(tasks:AbstractTaskList):int
    }

    +class AddTaskController extends Controller {
          +isThatAction(e:Actions):boolean
          +process(tasks:AbstractTaskList):int
    }

    +class AllCalendarController extends Controller{
           +isThatAction(e:Actions):boolean
           +process(tasks:AbstractTaskList):int
    }

    +class CalendarController extends Controller {
           +process(tasks:AbstractTaskList):int
    }

    +class DeleteTaskController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class EditTaskController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class ExitController extends SaveController {
          +process(tasks:AbstractTaskList):int
    }

    +class LoadController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class SaveController extends Controller {
          +process(tasks:AbstractTaskList):int
    }

    +class ShowAllTaskController extends Controller {
          +process(tasks:AbstractTaskList):int
    }
}

@enduml